apimock-data:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gcr.io/handy-honor-87017/apimock-data:latest
  stdin_open: true
apimock:
  ports:
  - 80:3000/tcp
  environment:
    STAGE: dev
  labels:
    io.rancher.sidekicks: apimock-data
    io.rancher.container.pull_image: always
  tty: true
  image: coleca/apimock
  volumes_from:
  - apimock-data
  labels:
    io.rancher.sidekicks: apimock-data
  stdin_open: true
apiproxy:
  ports:
  - 9300:80/tcp
  environment:
    STAGE: dev
    TEMPLATE_NGINX_HTML: '1'
    THREESCALE_SHARED_SECRET_TOKEN: 908jhsdfbk23js8s02!
    THREESCALE_PROVIDER_KEY: bb98017c2f7d07313a31d5b5d6ecce65
    THREESCALE_SERVICE_ID: '2555417723340'
    BACKEND_SERVER_ADDRESS: apimock
  labels:
    io.rancher.container.pull_image: always
  image: gcr.io/handy-honor-87017/apiproxy:latest
